"""Generate SMH Panel 'UI environments' data from the HyprPanel themes collection.

Reads every *.json theme in the given HyprPanel themes directory and emits an
ES module with one skin entry per theme (base / _split / _vivid variants kept).

Usage:
    python tools/generate_skins.py <hyprpanel-themes-dir> <output-js-path>
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HEX_RE = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")


def pick(theme: dict, *keys: str) -> str | None:
    for key in keys:
        value = theme.get(key)
        if isinstance(value, str) and HEX_RE.match(value.strip()):
            return value.strip()
    return None


def pretty_name(stem: str) -> tuple[str, str]:
    variant = "base"
    for suffix, label in (("_split", "Split"), ("_vivid", "Vivid")):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            variant = label.lower()
    words = stem.split("_")
    name = " ".join(w.capitalize() for w in words)
    name = name.replace("Rose Pine", "Rosé Pine")
    if variant == "split":
        name += " (Split)"
    elif variant == "vivid":
        name += " (Vivid)"
    return name, variant


def build_palette(theme: dict) -> dict:
    bg = pick(theme, "theme.bar.menus.background", "theme.bar.background", "theme.bar.buttons.background") or "#14161c"
    panel = pick(theme, "theme.bar.menus.cards", "theme.bar.menus.menu.notifications.card") or bg
    panel2 = pick(theme, "theme.bar.buttons.background", "theme.bar.buttons.icon_background") or panel
    border = pick(theme, "theme.bar.menus.border.color", "theme.notification.border", "theme.bar.border.color") or "#33384a"
    text = pick(theme, "theme.bar.menus.text", "theme.bar.buttons.text") or "#e8ecf3"
    muted = pick(theme, "theme.bar.menus.dimtext", "theme.bar.menus.feinttext") or "#8a93a7"
    accent = pick(
        theme,
        "theme.bar.menus.label",
        "theme.bar.buttons.active",
        "theme.bar.buttons.text",
        "theme.bar.menus.listitems.active",
    ) or "#4c8dff"
    accent2 = pick(
        theme,
        "theme.bar.menus.slider.primary",
        "theme.bar.menus.progressbar.foreground",
        "theme.bar.buttons.icon",
    ) or accent
    ok = pick(theme, "theme.bar.buttons.modules.netstat.border", "theme.bar.buttons.modules.netstat.icon") or "#3ecf8e"
    warn = pick(theme, "theme.bar.buttons.modules.ram.border", "theme.bar.buttons.modules.ram.icon") or "#f5a623"
    err = pick(
        theme,
        "theme.bar.menus.menu.notifications.clear",
        "theme.bar.menus.menu.dashboard.powermenu.shutdown",
        "theme.notification.close_button.background",
    ) or "#ff6b6b"
    return {
        "bg": bg,
        "panel": panel,
        "panel2": panel2,
        "border": border,
        "text": text,
        "muted": muted,
        "accent": accent,
        "accent2": accent2,
        "ok": ok,
        "warn": warn,
        "err": err,
    }


def main() -> int:
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])
    skins = []
    for path in sorted(src.glob("*.json")):
        try:
            theme = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            print(f"skip {path.name}: {exc}")
            continue
        if not isinstance(theme, dict):
            continue
        name, variant = pretty_name(path.stem)
        palette = build_palette(theme)
        skins.append(
            {
                "id": "hypr-" + path.stem.replace("_", "-"),
                "name": name,
                "source": "HyprPanel",
                "variant": variant,
                "pal": palette,
            }
        )

    lines = [
        "/* GC generated by tools/generate_skins.py from the HyprPanel themes collection",
        "   (sample projects provided by the user; 45 JSON palettes). */",
        "export const HYPR_SKINS = [",
    ]
    for skin in skins:
        lines.append("  " + json.dumps(skin, ensure_ascii=False) + ",")
    lines.append("];")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} with {len(skins)} skins")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
